import fs from 'node:fs';import os from 'node:os';import path from 'node:path';import assert from 'node:assert/strict';import {spawnSync} from 'node:child_process';
const root=fs.mkdtempSync(path.join(os.tmpdir(),'mgf-manual-release-'));const write=(p,data)=>{const f=path.join(root,p);fs.mkdirSync(path.dirname(f),{recursive:true});fs.writeFileSync(f,typeof data==='string'?data:JSON.stringify(data))};const read=p=>JSON.parse(fs.readFileSync(path.join(root,p)));const run=(script,args=[])=>spawnSync(process.execPath,[path.join(root,'factory/lib',script+'.mjs'),...args],{encoding:'utf8',env:{...process.env,INCLUDE_UNPUBLISHED:'0'}});let checks=0;const check=(label,fn)=>{fn();checks++;console.log('PASS '+label)};
try{
for(const file of ['publish-game.mjs','build-index.mjs','verify-catalog.mjs','paths.mjs'])write('factory/lib/'+file,fs.readFileSync('factory/lib/'+file,'utf8'));
write('curriculum/2022-elementary-math.json',{units:[{id:'test-unit',order:1}],standards:[]});write('factory/state/queue.json',{produced:[],failed:[],mechanic_history:[],palette_history:[]});for(const file of ['index.html','thumb.png','square.png'])write('public/g/fixture-game/'+file,'fixture');
write('public/g/fixture-game/meta.json',{slug:'fixture-game',title:'Fixture railway',grade:4,semester:2,unit:{id:'test-unit',title:'Fractions'},mechanic:'fixture-rail',qa:{score:0,gate:80,passed:false}});
const publish=(...args)=>run('publish-game',['fixture-game',...args]);const snapshot=()=>['factory/state/queue.json','public/g/fixture-game/meta.json'].map(p=>fs.readFileSync(path.join(root,p),'utf8'));
let before=snapshot();check('default score 79 rejected without writes',()=>{assert.notEqual(publish('--score','79').status,0);assert.deepEqual(snapshot(),before)});
check('gate 79 rejected even with explicit approval',()=>{assert.notEqual(publish('--score','79','--gate','79','--manual-approval','explicit request').status,0);assert.deepEqual(snapshot(),before)});
check('blank approval rejected without writes',()=>{assert.notEqual(publish('--score','79','--manual-approval',' \n ').status,0);assert.deepEqual(snapshot(),before)});
check('approval option without value rejected',()=>{assert.notEqual(publish('--score','79','--manual-approval').status,0);assert.deepEqual(snapshot(),before)});
check('explicit score 79 released honestly',()=>{const r=publish('--score','79','--manual-approval',' User requested release below 80 ');assert.equal(r.status,0,r.stderr);assert.match(r.stdout,/User requested release below 80/);const qa=read('public/g/fixture-game/meta.json').qa;assert.equal(qa.score,79);assert.equal(qa.gate,80);assert.equal(qa.passed,false);assert.equal(qa.manual_release.approved,true);assert.equal(qa.manual_release.reason,'User requested release below 80');assert.ok(qa.manual_release.at);assert.deepEqual(read('factory/state/queue.json').produced[0].manual_release,qa.manual_release)});
check('build and verification include approved game',()=>{assert.equal(read('public/catalog.json').count,1);assert.equal(read('public/catalog.json').games[0].qa.passed,false);assert.equal(run('verify-catalog').status,0);assert.match(fs.readFileSync(path.join(root,'public/index.html'),'utf8'),/Fixture railway/)});
check('repeated explicit publication is idempotent',()=>{assert.equal(publish('--score','79','--manual-approval','same explicit request').status,0);const q=read('factory/state/queue.json');assert.equal(q.produced.length,1);assert.equal(q.mechanic_history.length,1);assert.equal(read('public/catalog.json').count,1)});
before=snapshot();check('previous approval cannot authorize next 79 invocation',()=>{assert.notEqual(publish('--score','79').status,0);assert.deepEqual(snapshot(),before)});
check('missing approved catalog diagnosis recognizes manual release',()=>{write('public/catalog.json',{count:0,games:[]});const r=run('verify-catalog');assert.notEqual(r.status,0);assert.match(r.stderr,/same explicit request/);assert.doesNotMatch(r.stderr,/meta.qa.passed !== true/)});
check('normal score 80 passes and clears previous exception',()=>{const r=publish('--score','80');assert.equal(r.status,0,r.stderr);const qa=read('public/g/fixture-game/meta.json').qa;assert.equal(qa.score,80);assert.equal(qa.passed,true);assert.equal(qa.manual_release,undefined);assert.equal(read('factory/state/queue.json').produced[0].manual_release,undefined);assert.equal(run('verify-catalog').status,0)});
console.log(`${checks} isolated CLI regression checks passed. No live queue/catalog writes.`);
}finally{fs.rmSync(root,{recursive:true,force:true})}
